"""First-revision

Revision ID: 02979cf0af12
Revises: c87fa6fef988
Create Date: 2024-06-25 19:14:29.483975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02979cf0af12'
down_revision: Union[str, None] = 'c87fa6fef988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('institution_tab_registration_id_fkey', 'institution_tab', type_='foreignkey')
    op.drop_column('institution_tab', 'registration_id')
    op.add_column('medication_tab', sa.Column('medication_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_tab', 'medication_name')
    op.add_column('institution_tab', sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('institution_tab_registration_id_fkey', 'institution_tab', 'clinician_tab', ['registration_id'], ['registration_id'])
    # ### end Alembic commands ###
