"""First-revision

Revision ID: 2ce69accc27c
Revises: 
Create Date: 2024-06-20 07:25:44.087971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce69accc27c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician',
    sa.Column('registration_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_table('medication',
    sa.Column('code_id', sa.String(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.Column('code_iso_name', sa.String(), nullable=True),
    sa.Column('strength_value', sa.SmallInteger(), nullable=True),
    sa.Column('strenght_unit', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('form', sa.Enum('POWDER', 'TABLET', 'CAPSULE', 'SYRUP', name='formtype'), server_default='CAPSULE', nullable=False),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'PSI', 'BAR', 'KPA', name='GenderType'), server_default='FEMALE', nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('medication_request',
    sa.Column('medication_request_id', sa.String(), nullable=False),
    sa.Column('clinician_reg_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('medication_code_id', sa.String(), nullable=True),
    sa.Column('reason_of_prescription', sa.TEXT(), nullable=True),
    sa.Column('prescription_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('frequency', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'CANCELLED', 'COMPLETED', name='status'), server_default='ACTIVE', nullable=False),
    sa.ForeignKeyConstraint(['clinician_reg_id'], ['clinician.registration_id'], ),
    sa.ForeignKeyConstraint(['medication_code_id'], ['medication.code_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('medication_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_request')
    op.drop_table('patient')
    op.drop_table('medication')
    op.drop_table('clinician')
    # ### end Alembic commands ###
