"""First-revision

Revision ID: 4e29e1f8b36c
Revises: f0b5f544cb7c
Create Date: 2024-06-28 08:31:54.315025

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e29e1f8b36c"
down_revision: Union[str, None] = "f0b5f544cb7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prescription_tab", sa.Column("medication_refrence", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "prescription_tab",
        "medication_tab",
        ["medication_refrence"],
        ["medication_reference"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prescription_tab", type_="foreignkey")
    op.drop_column("prescription_tab", "medication_refrence")
    # ### end Alembic commands ###
