"""First-revision

Revision ID: 6e40c68850c7
Revises: adaa8ce77ec1
Create Date: 2024-06-27 08:41:33.531669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e40c68850c7'
down_revision: Union[str, None] = 'adaa8ce77ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apointment_tab', sa.Column('institution_refrence', sa.Integer(), nullable=True))
    op.drop_constraint('apointment_tab_intitution_refrence_fkey', 'apointment_tab', type_='foreignkey')
    op.create_foreign_key(None, 'apointment_tab', 'institution_tab', ['institution_refrence'], ['id'])
    op.drop_column('apointment_tab', 'intitution_refrence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apointment_tab', sa.Column('intitution_refrence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'apointment_tab', type_='foreignkey')
    op.create_foreign_key('apointment_tab_intitution_refrence_fkey', 'apointment_tab', 'institution_tab', ['intitution_refrence'], ['id'])
    op.drop_column('apointment_tab', 'institution_refrence')
    # ### end Alembic commands ###
