"""First-revision

Revision ID: c87fa6fef988
Revises: fd57cb72ee87
Create Date: 2024-06-25 12:40:51.138308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87fa6fef988'
down_revision: Union[str, None] = 'fd57cb72ee87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinician_tab', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clinician_tab', 'institution_tab', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clinician_tab', type_='foreignkey')
    op.drop_column('clinician_tab', 'institution_id')
    # ### end Alembic commands ###
