"""First-revision

Revision ID: cdb16ea3b8a5
Revises: 02979cf0af12
Create Date: 2024-06-25 19:20:05.434035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb16ea3b8a5'
down_revision: Union[str, None] = '02979cf0af12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medication_tab', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'active_ingredient_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'excipient_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'other_name_of_active_ingredient',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'abbreviated_name_of_active_ingredient',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'chemical_formula',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'peculiar_part_of_drug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'smell',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'taste',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'usage_of_excipient',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'indications',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'contraindications',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'is_allowed_for_children',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'medication_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'medication_sub_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'medication_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'frequency',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('medication_tab', 'dosage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'side_effects',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'storage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medication_tab', 'is_fda_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_nhs_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_emergency_medicine',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_controlled_drug',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_generic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_over_the_counter',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_herbal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_homeopathic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_unlicensed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_orphan_drug',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_biological',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_trial_drug',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_medical_gas',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_medical_radioisotope',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medication_tab', 'is_medical_radioactive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medication_tab', 'is_medical_radioactive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_medical_radioisotope',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_medical_gas',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_trial_drug',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_biological',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_orphan_drug',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_unlicensed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_homeopathic',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_herbal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_over_the_counter',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_generic',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_controlled_drug',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_emergency_medicine',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_nhs_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'is_fda_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'storage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'side_effects',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'dosage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'frequency',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('medication_tab', 'medication_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'medication_sub_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'medication_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'is_allowed_for_children',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medication_tab', 'contraindications',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'indications',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'usage_of_excipient',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'taste',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'smell',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'peculiar_part_of_drug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'chemical_formula',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'abbreviated_name_of_active_ingredient',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'other_name_of_active_ingredient',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'excipient_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'active_ingredient_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medication_tab', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
