"""First-revision

Revision ID: d443e1c8f739
Revises: 6e40c68850c7
Create Date: 2024-06-27 10:44:55.780636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd443e1c8f739'
down_revision: Union[str, None] = '6e40c68850c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_trial_tab', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('clinical_trial_tab', sa.Column('updated_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_trial_tab', 'updated_on')
    op.drop_column('clinical_trial_tab', 'created_on')
    # ### end Alembic commands ###
