"""First-revision

Revision ID: e7742e1587eb
Revises: c1dd06286db4
Create Date: 2024-07-04 20:30:32.558585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7742e1587eb'
down_revision: Union[str, None] = 'c1dd06286db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_tab', sa.Column('image_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'image_tab', ['image_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_tab', type_='unique')
    op.drop_column('image_tab', 'image_code')
    # ### end Alembic commands ###
