"""First-revision

Revision ID: ecbb9ec9a231
Revises: 912ccb3e7b1f
Create Date: 2024-06-26 15:41:15.078674

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecbb9ec9a231"
down_revision: Union[str, None] = "912ccb3e7b1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
