"""First-revision

Revision ID: f5552635568d
Revises: 17046dafbd04
Create Date: 2024-06-26 15:03:21.729814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5552635568d'
down_revision: Union[str, None] = '17046dafbd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_tab', sa.Column('clinician_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient_tab', 'clinician_tab', ['clinician_id'], ['registration_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_tab', type_='foreignkey')
    op.drop_column('patient_tab', 'clinician_id')
    # ### end Alembic commands ###
