"""First-revision

Revision ID: fd57cb72ee87
Revises: f9cd41eaf42b
Create Date: 2024-06-24 21:12:12.449970

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd57cb72ee87"
down_revision: Union[str, None] = "f9cd41eaf42b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clinician_tab", "institution_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinician_tab",
        sa.Column("institution_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
