"""First-revision

Revision ID: ff67321aeb7d
Revises: 13970809280f
Create Date: 2024-06-23 19:57:50.592119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff67321aeb7d'
down_revision: Union[str, None] = '13970809280f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
